<a href="https://colab.research.google.com/github/NandaKori/struktur_data/blob/main/latihan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Mengimpor library numpy
import numpy as np

# Membuat array 2D (matriks) dengan ukuran 3x3
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Array 2D:")
print(array_2d)

# Membuat array 3D dengan ukuran 2x3x4
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print("\nArray 3D:")
print(array_3d)


Array 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 3D:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
import numpy as np

# Membuat array 2D dengan nama-nama buah
buah = np.array([["Apel", "Mangga", "Jeruk"],
                 ["Pisang", "Semangka", "Melon"]])

# Cetak array buah
print("Array Buah 2D:")
print(buah)


Array Buah 2D:
[['Apel' 'Mangga' 'Jeruk']
 ['Pisang' 'Semangka' 'Melon']]


In [ ]:
data = [[1,2,3], [4,5,6]]

print(data[0][0])
print(data[0][1])
print(data[0][2])
print(data[1][0])
print(data[1][1])
print(data[1][2])

1
2
3
4
5
6


In [ ]:
data = [[[1, 2, 3], [4, 5, 6]], [['a', 'b', 'c'], ['d', 'e', 'f']]]

print(data[0][0][0])
print(data[0][0][1])
print(data[0][0][2])
print(data[0][1][0])
print(data[0][1][1])
print(data[0][1][2])
print(data[1][0][0])
print(data[1][0][1])
print(data[1][0][2])
print(data[1][1][0])
print(data[1][1][1])
print(data[1][1][2])


1
2
3
4
5
6
a
b
c
d
e
f


In [ ]:
data = [[1,2,3], [4,5,6], [7,8,9]]

for i in  range(len(data)):
  for j in range(len(data[i])):
    print(data[i][j])

1
2
3
4
5
6
7
8
9


In [9]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(data)):
    total_per_baris = 0
    for j in range(len(data[i])):
        print(data[i][j])
        total_per_baris += data[i][j]
    print("Total per baris:", total_per_baris)


1
2
3
Total per baris: 6
4
5
6
Total per baris: 15
7
8
9
Total per baris: 24


In [14]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(data)):
    total = 0
    for j in range(len(data[i])):
        total = total + data[i][j]
    print('Total = ', total)


Total =  6
Total =  15
Total =  24


In [11]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for row in data:
    smallest = min(row)
    print("Data terkecil :", smallest)


Data terkecil : 1
Data terkecil : 4
Data terkecil : 7


In [12]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(data)):
    smallest = data[i][0]
    for j in range(1, len(data[i])):
        if data[i][j] < smallest:
            smallest = data[i][j]
    print("Data terkecil pada baris", i+1, ":", smallest)


Data terkecil pada baris 1 : 1
Data terkecil pada baris 2 : 4
Data terkecil pada baris 3 : 7


In [15]:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

for i in range(len(data)):
    min = 9999
    for j in range(len(data[i])):
        if(data[i][j] < min):
          min = data[i][j]
    print('Nilai Terkecil = ', min)

Nilai Terkecil =  1
Nilai Terkecil =  4
Nilai Terkecil =  7
