<a href="https://colab.research.google.com/github/NandaKori/struktur_data/blob/main/latuhan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Mengimpor library numpy
import numpy as np

# Membuat array 2D (matriks) dengan ukuran 3x3
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Array 2D:")
print(array_2d)

# Membuat array 3D dengan ukuran 2x3x4
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print("\nArray 3D:")
print(array_3d)


Array 2D:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 3D:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
import numpy as np

# Membuat array 2D dengan nama-nama buah
buah = np.array([["Apel", "Mangga", "Jeruk"],
                 ["Pisang", "Semangka", "Melon"]])

# Cetak array buah
print("Array Buah 2D:")
print(buah)


Array Buah 2D:
[['Apel' 'Mangga' 'Jeruk']
 ['Pisang' 'Semangka' 'Melon']]


In [ ]:
data = [[1,2,3], [4,5,6]]

print(data[0][0])
print(data[0][1])
print(data[0][2])
print(data[1][0])
print(data[1][1])
print(data[1][2])

1
2
3
4
5
6


In [ ]:
data = [[[1, 2, 3], [4, 5, 6]], [['a', 'b', 'c'], ['d', 'e', 'f']]]

print(data[0][0][0])
print(data[0][0][1])
print(data[0][0][2])
print(data[0][1][0])
print(data[0][1][1])
print(data[0][1][2])
print(data[1][0][0])
print(data[1][0][1])
print(data[1][0][2])
print(data[1][1][0])
print(data[1][1][1])
print(data[1][1][2])


1
2
3
4
5
6
a
b
c
d
e
f


In [ ]:
data = [[1,2,3], [4,5,6], [7,8,9]]

for i in  range(len(data)):
  for j in range(len(data[i])):
    print(data[i][j])

1
2
3
4
5
6
7
8
9
